name: Compile

on:
  push:
    branches:
      - release/*

concurrency:
  group: "indexer-compile"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.20

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Download dependencies
        run: go mod download

      - name: Create ui folder
        run: |
          mkdir _ui
          mkdir _ui/wallet
          cd _ui/wallet
          touch index.html

      - name: Build for Linux amd64
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 1
        run: |
          go build -v -o binaries/linux_amd64/indexer cmd/node/main.go
          go build -v -o binaries/linux_amd64/pqmigrator cmd/migrator/main.go

      - name: Make binaries executable
        run: |
          chmod +x binaries/linux_amd64/indexer
          chmod +x binaries/linux_amd64/pqmigrator

      - name: Install ARM compilation dependencies
        run: sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build for Linux arm64
        env:
          CC: aarch64-linux-gnu-gcc
          CXX: aarch64-linux-gnu-g++
          GOOS: linux
          GOARCH: aarch64
          CGO_ENABLED: 1
        run: |
          go build -v -o binaries/linux_arm64/indexer cmd/node/main.go
          go build -v -o binaries/linux_arm64/pqmigrator cmd/migrator/main.go

      - name: Make binaries executable
        run: |
          chmod +x binaries/linux_arm64/indexer
          chmod +x binaries/linux_arm64/pqmigrator

      - name: Configure Git
        run: |
          git config --global user.name 'Citizen Wallet Bot'
          git config --global user.email 'bot@citizenwallet.xyz'

      - name: Commit and push
        run: |
          git add -f binaries/*
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Add compiled binaries"
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
            git push origin $BRANCH_NAME
          fi
